linters:
  disable-all: true
  enable:
    - errcheck
    - exportloopref
    - gocritic
    - goimports
    - gosimple
    - govet
    - gosimple
    - ineffassign
    - misspell
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - tenv
    - unconvert
    - unused
    - usestdlibvars

linters-settings:
  goimports:
    local-prefixes: github.com/simplesurance/terraform-provider-bunnycdn


issues:
  exclude-use-default: false
